config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help",to: "static_pages#help"
    get "/about",to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :microposts, only: %i(create destroy)
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <%= link_to "Ruby on Rails Tutorial", Settings.urls.footer.tutorial %>by
    <%= link_to "Michael Hartl",Settings.urls.footer.author %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.about"), about_path %></li>
      <li><%= link_to t("static_pages.contact.contact"), contact_path %></li>
      <li><%= link_to t("static_pages.footer.news") ,Settings.urls.footer.news %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <%= link_to "English", locale: :en %>
  <%= link_to "Vietnamese", locale: :vi %>
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.header.home"), root_path %></li>
        <li><%= link_to t("static_pages.header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users.user"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t("users.account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("users.profile"), current_user %></li>
              <li><%= link_to t("users.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("users.logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static_pages.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %> <%= javascript_pack_tag "application",
    "data-turbolinks-track": "reload" %> <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %> <%= content_tag(:div, message, class: "alert
      alert-#{message_type}") %> <% end %> <%= yield %> <%= render "layouts/footer" %> <%=
      debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>